- name: output test 
  hosts: chkpmgmt
  tasks:
   - name: run uname thru awk 
     ansible.builtin.shell:  /usr/bin/uname -a | awk '{print $NF}'
     register: results
   - debug:
       var: results.stdout
